function scatter_bioactive(X1, Y1)
%CREATEFIGURE1(X1, Y1, S1, C1)
%  X1:  scatter x
%  Y1:  scatter y
%  S1:  scatter s
%  C1:  scatter c

%  Auto-generated by MATLAB on 15-Sep-2017 16:25:03

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create scatter
scatter(X1,Y1,...
    'MarkerEdgeColor',[0.635294117647059 0.0784313725490196 0.184313725490196],...
    'Marker','.');

% Uncomment the following line to preserve the X-limits of the axes
%xlim(axes1,[1e-16 1]);
%ylim(axes1,[1e-16 1]); 

% Set the remaining axes properties
set(axes1,'XGrid','on','XMinorGrid','on','XMinorTick','on','XScale','log',...
    'XTick',[0 1e-16 1e-06 0.001 1],'XTickLabel',{'0','1e-16','1e-6','1e-3','1'},...
    'YGrid','on','YMinorGrid','on','YMinorTick','on','YScale','log','YTick',...
    [0 1e-16 1e-06 0.001 1],'YTickLabel',{'0','1e-16','1e-06','1e-3','1'});
