drug_categories =      {'Angiogenesis',...
                        'Actin',...
                        'Cell Cycle',...
                        'Cytoskeletal Signaling',...
                        'MT',...
                        'DMSO',...
                        'DNA',...
                        'EstrogenR',...
                        'Glucocorticoid',...
                        'Retinoid',...
                        'EGFR',...
                        'GSK-3',...
                        'JAK/STAT',...
                        'MAPK',...
                        'MEK',...
                        'NF-?B',...
                        'ALK',...
                        'COX',...
                        'HMG-CoA Reductase',...
                        'BET',... 
                        'Epigenetic Reader Domain',...
                        'DNA Methyltransferase',...
                        'Histone Acetyltransferase',...
                        'HDAC',...
                        'Histone demethylases',...
                        'HistoneMT',...
                        'Sirtuin',...
                        'Apoptosis',...
                        'HSP90',...
                        'Proteasome',...
                        'Ubiquitin',...
                        'mTOR',...
                        'ER'}                        
                    
% drug_categories =      {'5-HT Receptor',......
%                         'Histamine Receptor',...
%                         'AChR',...
%                         'Angiogenesis',...
%                         'Actin',...
%                         'Cell Cycle',...
%                         'Cytoskeletal Signaling',...
%                         'MT',...
%                         'DMSO',...
%                         'DNA',...
%                         'PPAR',...
%                         'PARP',...    
%                         'Endocrinology & Hormones',...
%                         'EstrogenR',...
%                         'Glucocorticoid',...
%                         'Retinoid',...
%                         'GPCR & G Protein',...
%                         'EGFR',...
%                         'GSK-3',...
%                         'JAK/STAT',...
%                         'MAPK',...
%                         'MEK',...
%                         'NF-?B',...
%                         'ALK',...
%                         'Protein Tyrosine Kinase',...
%                         'COX',...
%                         'HMG-CoA Reductase',...
%                         'BET',... 
%                         'Epigenetic Reader Domain',...
%                         'DNA Methyltransferase',...
%                         'Histone Acetyltransferase',...
%                         'HDAC',...
%                         'Histone demethylases',...
%                         'HistoneMT',...
%                         'Sirtuin',...
%                         'Apoptosis',...
%                         'HSP90',...
%                         'Proteasome',...
%                         'Ubiquitin',...
%                         'mTOR',...
%                         'ER',...
%                         'Metabolism',...
%                         'Microbiology',...
%                         'Stem Cells &  Wnt',...
%                         'TGF-beta/Smad',...
%                         'Transmembrane Transporters'}
 
%                         'Neuronal Signaling',...
%                         'Others',...
%                         'PC',...