function createfigure(cdata1)
%CREATEFIGURE(CDATA1)
%  CDATA1:  image cdata

%  Auto-generated by MATLAB on 03-Apr-2017 18:03:17

% Create figure
figure1 = figure;
colormap(gray);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create image
image(cdata1,'Parent',axes1,'CDataMapping','scaled');

% Create title
title('Log P Values');

% Create ylabel
ylabel('Sorted by Pathway, XRCC5, NQO1');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0.5 4.5]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0.5 1835.5]);
box(axes1,'on');
axis(axes1,'ij');
% Set the remaining axes properties
set(axes1,'Layer','top','XTick',[1 2 3 4],'XTickLabel',...
    {'SET','S100A11','NQO1','XRCC5'},'YTick',...
    [44 73 134 171 237 305 362 396 418 457 539 558 570 793 1494 1583 1625 1724 1737 1756 1820 1835],...
    'YTickLabel',...
    {'Angiogenesis','Apoptosis','Cell Cycle','Cytoskeleton','DNA Damage','Endocrinology & Hormones','Epigenetics','GPCR & G Protein','JAK/STAT','MAPK','Metabolism','Microbiology','NF-kB','Neuronal Signaling','Others','PI3K/Akt/mTOR','Proteases','Protein Tyrosine Kinases','Stem Cells & Wnt','TGF-beta/Smad','Transmembrane Transporters','Ubiquitin'});
% Create colorbar
colorbar('peer',axes1);

ylim([1 1835])

